/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Carrera;

import javax.swing.JLabel;

/**
 *
 * @author lenin
 */
public class frmCarrera extends javax.swing.JFrame {

    /**
     * Creates new form frmCarrera
     */
    public frmCarrera() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Concierto de Megadeth");
    }

    public JLabel getPrimerAuto(){
        return primer_auto;
    }
    
    public JLabel getSegundoAuto(){
        return segundo_auto;
    }
    
    public JLabel getBArrera1(){
        return barrera1;
    }
    
    public JLabel getBArrera2(){
        return barrera2;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barrera1 = new javax.swing.JLabel();
        segundo_auto = new javax.swing.JLabel();
        primer_auto = new javax.swing.JLabel();
        barrera2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barrera1.setBackground(new java.awt.Color(102, 153, 255));
        barrera1.setOpaque(true);
        getContentPane().add(barrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 20, 220));

        segundo_auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Diseño sin título (1).png"))); // NOI18N
        getContentPane().add(segundo_auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 130));

        primer_auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Diseño sin título (1).png"))); // NOI18N
        getContentPane().add(primer_auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 150, 130));

        barrera2.setBackground(new java.awt.Color(102, 153, 255));
        barrera2.setOpaque(true);
        getContentPane().add(barrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 20, 220));

        jButton1.setText("Iniciar Simulacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Diseño sin título (5).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 220));

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 960, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        primer_auto.setLocation(0, primer_auto.getLocation().y);
        segundo_auto.setLocation(0, segundo_auto.getLocation().y);
        
        Carrera auto1=new Carrera (primer_auto,this);
        Carrera auto2=new Carrera (segundo_auto,this);
        
        auto1.start();
        auto2.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barrera1;
    private javax.swing.JLabel barrera2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel primer_auto;
    private javax.swing.JLabel segundo_auto;
    // End of variables declaration//GEN-END:variables

    Object getBarrera() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
